# Generated by Django 5.2.1 on 2025-05-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Is_Accepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
