# Generated by Django 5.2.1 on 2025-05-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CR_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
