# Generated by Django 5.2.1 on 2025-05-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vat_certificate_manager',
            name='Uploaded_At',
        ),
    ]
