# Generated by Django 5.2 on 2025-05-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_vat_certificate_manager_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vat_certificate_manager',
            name='File_Type',
            field=models.CharField(max_length=255),
        ),
    ]
