# Generated by Django 5.2.1 on 2025-05-30 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_vat_certificate_manager_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Message', models.TextField()),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Target_Type', models.CharField(choices=[('ALL', 'All Users'), ('SUPER', 'Super Users'), ('NORMAL', 'Normal Users'), ('SPECIFIC', 'Specific User')], default='SPECIFIC', max_length=10)),
                ('User', models.ForeignKey(blank=True, db_column='User_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationReadStatus',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Is_Read', models.BooleanField(default=False)),
                ('Read_At', models.DateTimeField(blank=True, null=True)),
                ('Notification', models.ForeignKey(db_column='Notification_Id', on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='User.notification')),
                ('User', models.ForeignKey(db_column='User_Id', on_delete=django.db.models.deletion.CASCADE, related_name='notification_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Read Status',
                'verbose_name_plural': 'Notification Read Statuses',
                'db_table': 'notification_read_status',
                'unique_together': {('User', 'Notification')},
            },
        ),
    ]
