# Generated by Django 5.2.1 on 2025-05-28 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tender', '0002_tender_files_uploaded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bit',
            fields=[
                ('bit_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bits', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(db_column='tender_id', on_delete=django.db.models.deletion.CASCADE, related_name='bits', to='Tender.tender')),
            ],
        ),
        migrations.CreateModel(
            name='Bit_Files',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('file_type', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('file_data', models.BinaryField()),
                ('Uploaded_At', models.DateTimeField(auto_now_add=True)),
                ('bit', models.ForeignKey(db_column='bit_id', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Bit.bit')),
            ],
        ),
    ]
