# Generated by Django 5.2.1 on 2025-06-23 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('tender_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tender_Files',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('file_data', models.BinaryField()),
                ('Uploaded_At', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(db_column='tender_id', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Tender.tender')),
            ],
        ),
    ]
